#!/usr/bin/perl

use strict;
use warnings;
use version;	our $VERSION = qv('5.16.0');
use Text::CSV	1.32;
use Statistics::R;

my $COMMA = q{,};

my @records;
my @return_records;
my $record_count = -1;
my $return_count = -1;
my @ref_date;
my @geo;
my @violations;
my @sta;
my @vector;
my @coordinate;
my @value;
my $code = "2.1.1";
my $year = "1998";
my $year_2 = "2015"; 
my @found;
my $count = 0;
my $geo_2;
my $sta_2;
my $violations_2;
my $temp;
my $max;
my @year_array;
my $csv	  = Text::CSV->new({ sep_char => $COMMA });

if ($year > $year_2) {
	$temp = $year;
	$year = $year_2;
	$year_2 = $temp;
}

$temp = $year;

open my $file_fh, '<', "02520051-eng.csv" or 
	die "Unable to open file: 02520051-eng.csv\n";

print ("Loading...\n");

@records = <$file_fh>;

foreach my $file_record (@records) {
	if ($csv->parse($file_record)) {
		my @master_fields = $csv->fields();
		$record_count++;
		$ref_date[0]	= $master_fields[0];
		$geo[0]	 		= $master_fields[1];
		$violations[0]  = $master_fields[2];
		$sta[0]	  		= $master_fields[3];
		$vector[0]	 	= $master_fields[4];
		$coordinate[0]  = $master_fields[5];
		$value[0]	 	= $master_fields[6];
		if ($coordinate[0] eq $code && $ref_date[0] == $temp) {
			print "$sta[0] of $violations[0] in $geo[0] is $value[0] in the year $temp\n";
			$found[$count] = $value[0];
			$geo_2 = $geo[0];
			$sta_2 = $sta[0];
			$violations_2 = $violations[0];
			$count++;
			$temp++;
			if ($temp > 2015) {
				last;
			}
		}
	} else {
		warn "Line/record could not be parsed: $records[$record_count]\n"; 
	}
} 

close $file_fh or
	die "Unable to close: 02520051-eng.csv\n";

$count--;

$temp = $year;

open my $fh, '>', 'Trend.csv';

print $fh ("\"Year\", \"Value\"\n");

for my $x (0..$count) {
	$year_array[$x] = $year;
	print $fh ("$year, $found[$x]\n");
	$year++; 
}

 close $fh;

my $R = Statistics::R->new();

# Set up the PDF file for plots
$R->run(qq`pdf('Graph.pdf' , paper="letter")`);

# Load the plotting library
$R->run(q`library(ggplot2)`);

# read in data from a CSV file
$R->run(qq`data <- read.csv('Trend.csv')`);

# plot the data as a line plot with each point outlined
$R->run(q`ggplot(data, aes(x=Year, y=Value, group=1)) + geom_line() + geom_point(size=2) + ggtitle("Crime Trend Within the Given Years (Line)") + ylab("Incidence of Crimes") + scale_y_continuous(breaks=c(0,1,2,3,4,5,6,7,8), labels=c("None", "> 2000", "1000-2000", "500-999", "200-499", "100-199", "50-99", "11-49", "1-10")) `);
$R->run(q`ggplot(data, aes(x=Year, y=Value)) + geom_bar(stat="identity")`);
# close down the PDF device
$R->run(q`dev.off()`);

$R->stop();

